{
  "Comments": [
      "1. The 'Share' field is optional. It defaults to '\\\\' + Machine + '\\SwServers\\' + Account.",
      "2. Please, keep the list below sorted by account name.",
	  "SWRunner: SWRunner recognises 'Customer', 'WSPort', 'Name', 'Comments' fields",
	  "Parameters for deploy: 'GitBranch', 'CopyJava', 'RepoCore', 'BuildRecipient', 'RunBroker', 'NeedTest', 'AccountDev', 'PasswordDev', 'RepoSwJar'"
    ],
  "SW_AQSC_2020C":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_AQSC_26":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "RSSC", "GitBranch": "26.develop" },
  "SW_AQSC_30":        			{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "RSSC", "GitBranch": "30.develop", "CopyJava": "true", "RepoCore": "sw-core-30" },
  "SW_ATLANTIS_26":    			{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "RSSC", "GitBranch": "26.develop", "CopyJava": "true" },
  "SW_ATLANTIS_30":    		 	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "RSSC", "GitBranch": "30.develop", "CopyJava": "true" },
  "SW_BLM_008":  				{ "Machine": "BizLogicMig.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "CopyJava": "true", "RepoCore": "sw-blm-008", "BuildRecipient": "dimas@versonix.com" },
  "SW_BLM_008_DELPHI":  	  	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "CopyJava": "true", "RepoCore": "sw-blm-008", "BuildRecipient": "dimas@versonix.com" },
  "SW_BLM_008_30_DELPHI":      	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9143", "TNSName": "ORADEV" },
  "SW_BLM_008_30_SM_RELEASE":  	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV" },
  "SW_CCI_26_AUTOTESTS":        { "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "26.develop" },
  "SW_CCI_26":       			{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "26.develop" },
  "SW_CCI_28_AUTOTESTS":        { "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "28.develop" },
  "SW_CCI_28":        			{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "28.develop" },
  "SW_CCI_30_AUTOTESTS":		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "30.develop" },
  "SW_CCI_30":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "30.develop" },
  "SW_CCI_MAIN":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "develop", "RepoCore": "sw-core-MAIN" },
  "SW_CLST_2020C":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9692", "TNSName": "ORAUTF8" },
  "SW_DCL_2020":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "DCL", "GitBranch": "2020.develop", "CopyJava": "true" },
  "SW_DCL_2020B":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_DCL_2020C":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9086", "TNSName": "ORAUTF8" },
  "SW_DCL_30":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "DCL", "GitBranch": "30.develop", "CopyJava": "true" },
  "SW_DCL_MAIN":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9654", "TNSName": "ORAUTF8", "Customer": "DCL", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "CopyJava": "true" },
  "SW_DEMO_26":      	 		{ "Machine": "APPS-MAIN-05.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "26.develop"  },
  "SW_DEMO_29":      	 		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "29.develop"  },
  "SW_DEMO_30":      	 		{ "Machine": "VXS-DEMO.VERSONIX.COM", "TNSName": "ORADEMO", "Customer": "CCI", "GitBranch": "30.develop", "RepoCore": "sw-core-30"  },
  "SW_DEMO_FERRY_26":      	 	{ "Machine": "APPS-MAIN-10.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "26.develop"  },
  "SW_DEMO_FERRY_29":      	 	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "29.develop"  },
  "SW_DEMO_FERRY_30":      	 	{ "Machine": "VXS-DEMO.VERSONIX.COM", "TNSName": "ORADEMO", "Customer": "CCI", "GitBranch": "30.develop", "RepoCore": "sw-core-30"  },
  "SW_DEMO_MAIN":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "RSSC", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "CopyJava": "true"  },
  "SW_DEV_2020":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "DCL", "GitBranch": "2020.develop" },
  "SW_DEV_2020B":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_DEV_2020C":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9066", "TNSName": "ORAUTF8" },
  "SW_DEV_28":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "CCI", "GitBranch": "28.develop" },
  "SW_DEV_29":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_DEV_30":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "LINDBLAD", "GitBranch": "30.develop" },
  "SW_DREAMUSA_30":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_FERRY_DEMO":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_GQL_TEST":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_HAVILA_2020C":    		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9700", "TNSName": "ORAUTF8" },
  "SW_HAVILA_30":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9582", "TNSName": "ORAUTF8", "Customer": "RSSC", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "CopyJava": "true" },
  "SW_HAVILA_30_AUTOTESTS":		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "RSSC", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "CopyJava": "true" },
  "SW_HRG_130120":      		{ "Machine": "APPS-MAIN-07.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "HRG", "RepoCore": "sw-core-130120", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com']" },
  "SW_HRG_2020C":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9696", "TNSName": "ORADEV" },
  "SW_HRG_26":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "HRG", "GitBranch": "26.develop" },
  "SW_HRG_PROD":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9596", "TNSName": "ORADEV" },
  "SW_LINDBLAD_30":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "LINDBLAD", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "CopyJava": "true" },
  "SW_LINDBLAD_MAIN":   		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "RSSC", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "CopyJava": "true"  },
  "SW_MAIN_DAILY_TEST": 		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_MAIN_DEV":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9630", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "CopyJava": "true", "RunBroker": "Y", "NeedTest": "true", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com', 'eugenen@versonix.com']" },
  "SW_MAIN_PREQA":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9606", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "develop", "CopyJava": "true", "RunBroker": "Y", "NeedTest": "true", "BuildRecipient": "eugenen@versonix.com" },
  "SW_MAIN_QA":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9642", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "CopyJava": "true", "RunBroker": "Y", "NeedTest": "true", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com', 'eugenen@versonix.com']", "AccountDev": "SW_MAIN_DEV", "PasswordDev": "nav" },
  "SW_MAIN_QA_RECEIPT": 		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "12000", "TNSName": "ORADEV" },
  "SW_MAIN_QA_DELPHI":  		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "develop", "RepoCore": "sw-core-MAIN", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com', 'eugenen@versonix.com']", "AccountDev": "SW_MAIN_DEV", "PasswordDev": "nav" },
  "SW_MAIN_TRAINING":   		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_MSC_30":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_MSC_2020C":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "7879", "TNSName": "ORAUTF8"},
  "SW_OTA_TEST":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_OTA_TEST_26":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_OTA_TEST_28":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_OTA_TEST2":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_SC_SANDBOX":           	{ "Machine": "APPS-MAIN-11.VERSONIX.COM", "Customer": "SC", "RepoCore": "sw-core-MAIN" },
  "SW_SC_26":           		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "STAR", "GitBranch": "26.develop" },
  "SW_SC_30":           		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "STAR", "GitBranch": "30.develop" },
  "SW_SC_2020C":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "7899", "TNSName": "ORAUTF8"},
  "SW_SC_MAIN":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "STAR", "GitBranch": "develop" },
  "SW_SC_PROD":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_SILJA_24":        		{ "Machine": "APPS-MAIN-09.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "RepoCore": "sw-core-24", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com']" },
  "SW_SILJA_26":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "26.develop", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com']" },
  "SW_SILJA_26_JAVA":        	{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9626", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "26.develop", "RepoCore": "sw-core-26", "RunBroker": "N", "CopyJava": "true", "NeedTest": "true" },
  "SW_SILJA_27":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "27.develop", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com']"  },
  "SW_SILJA_28":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "28.develop"  },
  "SW_SILJA_30":        		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com', 'eugenen@versonix.com']", "AccountDev": "SW_SILJA_30", "PasswordDev": "nav", "RepoSwJar": "_REPO_SW_JAR=$WORKSPACE\\..\\sw-inventory" }, 
  "SW_SILJA_30_JAVA":   		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9608", "TNSName": "ORADEV", "Customer": "VX", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "BuildRecipient": "['$EMAIL_CORE_BUILD_ENGINEERS', 'gennadyz@versonix.com', 'eugenen@versonix.com']", "AccountDev": "SW_SILJA_30_JAVA", "PasswordDev": "nav", "CopyJava": "true", "NeedTest": "true" }, 
  "SW_SILJA_2020B":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9004", "TNSName": "ORADEV" },
  "SW_SILJA_2020B_JAVA":		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "8966", "TNSName": "ORADEV" },
  "SW_SILJA_2020C_JAVA":		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9107", "TNSName": "ORADEV" },
  "SW_SILJA_2020C":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9123", "TNSName": "ORADEV" },
  "SW_SILJA_MAIN":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "develop", "RepoCore": "sw-core-MAIN" },
  "SW_SNCM_26":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SNCM", "GitBranch": "26.develop" },
  "SW_SNCM_30":         		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SNCM", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "CopyJava": "true" },
  "SW_SNCM_PROD":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_SPL_130120":       		{ "Machine": "APPS-MAIN-09.VERSONIX.COM", "Customer": "SPL", "RepoCore": "sw-core-130120" },
  "SW_SPL_2020C":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9698", "TNSName": "ORAUTF8" },
  "SW_SPL_26":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "CCI", "GitBranch": "26.develop" },
  "SW_SPL_30":          		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "SPL", "GitBranch": "30.develop", "RepoCore": "sw-core-30", "CopyJava": "true" },
  "SW_TEST_SUITE":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_TEST_DB_28":      		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "VX TEST SUITE", "GitBranch": "28.develop" },
  "SW_TESTDB_SETUP":    		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "Customer": "VX TEST SUITE" },
  "SW_VIRGIN_MAIN":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_VIRGIN_PROD":     		{ "Machine": "APPS-MAIN-01.VERSONIX.COM" },
  "SW_VIRGIN_26":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "26.develop" },
  "SW_VIRGIN_30_AUTOTESTS":		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "30.develop", "CopyJava": "true" },
  "SW_VIRGIN_30":       		{ "Machine": "APPS-MAIN-01.VERSONIX.COM", "WSPort": "9576", "TNSName": "ORADEV", "Customer": "SILJA", "GitBranch": "30.develop", "CopyJava": "true" }
}
