package textChangers;

import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.lang3.StringUtils;

public class CapitalizeInQuotes {

	public static void main(String[] args) {
		String toChange = "public static final String DTYPE_MANUAL_AUDIT_RESULTS_REVIEW = \"MANUAL_AUDIT_RESULTS_REVIEW\";\n" + 
				"	public static final String DTYPE_FILL_SITE_PROPERTY_URL = \"FILL_SITE_PROPERTY_URL\";\n" + 
				"	public static final String DTYPE_FETCH_DESC_FROM_SITE = \"FETCH_DESC_FROM_SITE\";\n" + 
				"	public static final String DTYPE_COPY_CONTACTS = \"COPY_CONTACTS\";\n" + 
				"	public static final String DTYPE_CHECK_IMAGE_MATCH = \"CHECK_IMAGE_MATCH\";\n" + 
				"	public static final String DTYPE_CHECK_DESCRIPTION = \"CHECK_DESCRIPTION\";\n" + 
				"	public static final String DTYPE_MANUAL_CHECK_IMAGES = \"MANUAL_CHECK_IMAGES\";\n" + 
				"	public static final String DTYPE_MAP_HOTEL_AMENITY = \"MAP_HOTEL_AMENITY\";\n" + 
				"	public static final String DTYPE_SITE_NOTIFICATION_EMAIL_REVIEW = \"SITE_NOTIFICATION_EMAIL_REVIEW\";\n" + 
				"	public static final String DTYPE_ADDRESS = \"ADDRESS\";\n" + 
				"	public static final String DTYPE_EMAIL = \"EMAIL\";\n" + 
				"	public static final String DTYPE_FAX = \"FAX\";\n" + 
				"	public static final String DTYPE_HOME_PAGE = \"HOME_PAGE\";\n" + 
				"	public static final String DTYPE_NAME = \"NAME\";\n" + 
				"	public static final String DTYPE_PHONE = \"PHONE\";\n" + 
				"	public static final String DTYPE_DOWNLOAD_ONE_IMAGE = \"DOWNLOAD_ONE_IMAGE\";\n" + 
				"	public static final String DTYPE_CHECK_IMAGE_UNIQUENESS = \"CHECK_IMAGE_UNIQUENESS\";\n" + 
				"	public static final String DTYPE_MARK_DUPLICATE_IMAGES = \"MARK_DUPLICATE_IMAGES\";\n" + 
				"	public static final String DTYPE_SEND_GENERATED_EMAIL = \"SEND_GENERATED_EMAIL\";\n" + 
				"	public static final String DTYPE_CATEGORY = \"CATEGORY\";\n" + 
				"	public static final String DTYPE_MAP_MP_CATEGORY = \"MAP_MP_CATEGORY\";\n" + 
				"	public static final String DTYPE_GEO_COORDINATES = \"GEO_COORDINATES\";\n" + 
				"	public static final String DTYPE_COLLECT_ORPHAN_IMAGES = \"COLLECT_ORPHAN_IMAGES\";\n" + 
				"	public static final String DTYPE_MAP_STAR_RATING = \"MAP_STAR_RATING\";\n" + 
				"	public static final String DTYPE_DOWNLOAD_IMAGES = \"DOWNLOAD_IMAGES\";\n" + 
				"	public static final String DTYPE_STAR_RATING = \"STAR_RATING\";\n" + 
				"	public static final String DTYPE_CHECK_MISSING_IMPORTANT_AMENITIES = \"CHECK_MISSING_IMPORTANT_AMENITIES\";\n" + 
				"	public static final String DTYPE_UNIQUE_IMAGES_VALIDITY = \"UNIQUE_IMAGES_VALIDITY\";\n" + 
				"	public static final String DTYPE_RETRIEVE_HOTEL_ID = \"RETRIEVE_HOTEL_ID\";\n" + 
				"	public static final String DTYPE_SEARCH_BY_ONE_NAME = \"SEARCH_BY_ONE_NAME\";\n" + 
				"	public static final String DTYPE_CHECK_APPROVED_AMENITIES = \"CHECK_APPROVED_AMENITIES\";\n" + 
				"	public static final String DTYPE_CHECK_IMPORTANT_AMENITIES = \"CHECK_IMPORTANT_AMENITIES\";\n" + 
				"	public static final String DTYPE_HOTEL_SEARCHES = \"HOTEL_SEARCHES\";\n" + 
				"	public static final String DTYPE_CHECK_MISSING_IMPORTANT_AMENITIES_COMP = \"CHECK_MISSING_IMPORTANT_AMENITIES_COMP\";\n" + 
				"	public static final String DTYPE_CHECK_APPROVED_AMENITIES_COMP = \"CHECK_APPROVED_AMENITIES_COMP\";\n" + 
				"	public static final String DTYPE_CHECK_FREE_TEXT_CHARACTERISTICS = \"CHECK_FREE_TEXT_CHARACTERISTICS\";";
		String toChange2 = "<changeSet id=\"RENAME_COPY_CONTACTS_TO_COPY_PROPERTY_DATA\" author=\"neznaev\">\n" + 
				"		<modifyDataType columnName=\"DTYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS','COPY_CONTACTS') not null\"\n" + 
				"			tableName=\"UNIT_TASKS\" />\n" + 
				"		<update tableName=\"UNIT_TASKS\">\n" + 
				"			<column name=\"DTYPE\" value=\"COPY_PROPERTY_DATA\" />\n" + 
				"			<where>DTYPE = 'COPY_CONTACTS'</where>\n" + 
				"		</update>\n" + 
				"		<modifyDataType columnName=\"DTYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS') not null\"\n" + 
				"			tableName=\"UNIT_TASKS\" />\n" + 
				"		<modifyDataType columnName=\"DTYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS','COPY_CONTACTS') not null\"\n" + 
				"			tableName=\"UNIT_MY_TASKS\" />\n" + 
				"		<update tableName=\"UNIT_MY_TASKS\">\n" + 
				"			<column name=\"DTYPE\" value=\"COPY_PROPERTY_DATA\" />\n" + 
				"			<where>DTYPE = 'COPY_CONTACTS'</where>\n" + 
				"		</update>\n" + 
				"		<modifyDataType columnName=\"DTYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS') not null\"\n" + 
				"			tableName=\"UNIT_MY_TASKS\" />\n" + 
				"		<modifyDataType columnName=\"TASK_TYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','COPY_CONTACTS') not null\"\n" + 
				"			tableName=\"MDS_MASTER_PROPERTY_TASK_INSTRUCTION\" />\n" + 
				"		<update tableName=\"MDS_MASTER_PROPERTY_TASK_INSTRUCTION\">\n" + 
				"			<column name=\"TASK_TYPE\" value=\"COPY_PROPERTY_DATA\" />\n" + 
				"			<where>TASK_TYPE = 'COPY_CONTACTS'</where>\n" + 
				"		</update>\n" + 
				"		<modifyDataType columnName=\"TASK_TYPE\"\n" + 
				"			newDataType=\"enum('CHECK_IMAGE_MATCH','COPY_PROPERTY_DATA','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','SITE_NOTIFICATION_EMAIL_REVIEW','ADDRESS','EMAIL','FAX','HOME_PAGE','NAME','PHONE','DOWNLOAD_ONE_IMAGE','CHECK_DESCRIPTION','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','STAR_RATING','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','SEND_GENERATED_EMAIL','CATEGORY','MAP_MP_CATEGORY','GEO_COORDINATES','UNIQUE_IMAGES_VALIDITY','RETRIEVE_HOTEL_ID','HOTEL_SEARCHES','SEARCH_BY_ONE_NAME','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES') not null\"\n" + 
				"			tableName=\"MDS_MASTER_PROPERTY_TASK_INSTRUCTION\" />\n" + 
				"		<modifyDataType columnName=\"TASK_TYPE\"\n" + 
				"			newDataType=\"enum('ADDRESS','CATEGORY','COPY_PROPERTY_DATA','CHECK_IMAGE_MATCH','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','DOWNLOAD_ONE_IMAGE','EMAIL','FAX','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','GEO_COORDINATES','HOME_PAGE','HOTEL_SEARCHES','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','MAP_MP_CATEGORY','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','NAME','PHONE','RETRIEVE_HOTEL_ID','SEARCH_BY_ONE_NAME','SEND_GENERATED_EMAIL','SITE_NOTIFICATION_EMAIL_REVIEW','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','STAR_RATING','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS','UNIQUE_IMAGES_VALIDITY','COPY_CONTACTS') not null\"\n" + 
				"			tableName=\"MDS_TASK_PREFERENCES\" />\n" + 
				"		<update tableName=\"MDS_TASK_PREFERENCES\">\n" + 
				"			<column name=\"TASK_TYPE\" value=\"COPY_PROPERTY_DATA\" />\n" + 
				"			<where>TASK_TYPE = 'COPY_CONTACTS'</where>\n" + 
				"		</update>\n" + 
				"		<modifyDataType columnName=\"TASK_TYPE\"\n" + 
				"			newDataType=\"enum('ADDRESS','CATEGORY','COPY_PROPERTY_DATA','CHECK_IMAGE_MATCH','CHECK_IMAGE_UNIQUENESS','COLLECT_ORPHAN_IMAGES','DOWNLOAD_IMAGES','DOWNLOAD_ONE_IMAGE','EMAIL','FAX','FETCH_DESC_FROM_SITE','FILL_SITE_PROPERTY_URL','GEO_COORDINATES','HOME_PAGE','HOTEL_SEARCHES','MANUAL_AUDIT_RESULTS_REVIEW','MANUAL_CHECK_IMAGES','MAP_HOTEL_AMENITY','MAP_MP_CATEGORY','MAP_STAR_RATING','MARK_DUPLICATE_IMAGES','NAME','PHONE','RETRIEVE_HOTEL_ID','SEARCH_BY_ONE_NAME','SEND_GENERATED_EMAIL','SITE_NOTIFICATION_EMAIL_REVIEW','CHECK_MISSING_IMPORTANT_AMENITIES','CHECK_APPROVED_AMENITIES','CHECK_IMPORTANT_AMENITIES','STAR_RATING','CHECK_MISSING_IMPORTANT_AMENITIES_COMP','CHECK_APPROVED_AMENITIES_COMP','CHECK_FREE_TEXT_CHARACTERISTICS','UNIQUE_IMAGES_VALIDITY') not null\"\n" + 
				"			tableName=\"MDS_TASK_PREFERENCES\" />\n" + 
				"	</changeSet>";
		String result = change(toChange, "\"");
		String result2 = change(toChange2, "'");
		System.out.println(result);
		System.out.println(result2);
	}

	private static String change(String toChange,String quotes) {
		 String pattern = quotes + ".+?" + quotes;
	        Pattern p = Pattern.compile(pattern);
	        Matcher m = p.matcher(toChange);
	        
	        while (m.find()) {
	        	String string = m.group();
	        	toChange = toChange.replaceAll(string, quotes + StringUtils.capitalize(string.toLowerCase(Locale.ENGLISH).replace('_', ' ').replaceAll(quotes, "") + quotes));
	        }
		return toChange;
	}
}
